deploy:
  password:
    secure: cEgE8MeoC+JezShSebYaSifRJAsN6JJ3uviZ7kFgoDep4qN8NZgAgqhPsLYXQihSpPLsi3lAr/O8+912T4LCC/lEwzpe+nSGbK8I0tf64hpxaPYMjM/3ugRZnOGQX+8IZJtaedLlq80mRpOnb+5S0pg3PBRjLq1JSzPxBI+OVdJbD2kODzJfFI4uiOfp/s/cSvsVbx/xchSFZCADNd7I3rrkA3OImfuxLMvBv3ZmT+EKYdOvrmNIGyJA5+SUDZJQY+XlGwq8WGfOQLcQMHgIKPG7hlT5M5SvBhpOWEwTZVCaBNefcNLMwO3wDWgGUYrHpzkv2K9PNvd72j90PVz+t8W7n8FKcwpZO7kZMc1xlHkWfpeP6kQrKRotROai7ypoJhJGo32qLBNuQMZ8XBe23Y3VAmTeQwa+zLbLvIkEZf5KXTU3BtweVrbXkyU23sqdAU2ZtqzSC00SYlCLFQhPGJW2uZoN1w6+tVUQA2c7QilptbPQ5rVWdvQQbAyR9KucMYI69OEd5xE8PCXoaCRJck5nWKZyM2ydJiUbiI2emm1q6UAAQhpWQrPKpBtOV2CDbd10zgA2ET7/7i684OLBOd9qHCEeowX51ZRMrzAZFmvfDlc6IR9eo6tm+Jr1pUzsIkfqIHqb0DLZVYGsDopZjyj70/5e8FgeIga3UIEgXqg=
  on:
    condition: $TOXENV == py35
    repo: pokey/listmatch
    tags: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: pokey
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=flake8
install: pip install -U tox
language: python
python: 3.5
script: tox -e ${TOXENV}
